# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jeffrey Auriemma's Blog
email: jdauriemma@gmail.com
description: thoughts on code, music and education
url: "http://bignimbus.github.io" # the base hostname & protocol for your site
twitter_username: jbones3000
github_username: bignimbus
linkedin_username: jeffreyauriemma
logo: "/assets/images/avatar.png"

# Build settings
markdown: redcarpet
redcarpet:
  extensions:
    - with_toc_data
sass:
  sass_dir: _sass
gems:
  - jekyll-archives
  - jekyll-paginate
paginate: 10
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    tag: '/tag/:name/'
    categories: '/category/:name/'
