# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jeff's Blog Experiment
email: jdauriemma@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  a proof of concept
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bignimbus.github.io" # the base hostname & protocol for your site
twitter_username: jbones3000
github_username: bignimbus 

# Build settings
markdown: kramdown
